name: run bot script

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 * * * *' # At 05 minute of Every hour
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system --deploy
          
      - name: execute py script # run main.py
        env:
          apiKey: ${{ secrets.apiKey }}
          secret: ${{ secrets.secret }}
          password: ${{ secrets.password }}

        run: make run
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 